token = "sample token file here"
twitchBotId = "used in the BotRespond command"
warcraftLogsAPI = "used to access warcraft logs"
serverDiscId = "this should be an int, not a string"
raidlogsChannelId = "this should be an int, not a string"
"""Rename this file to config.py and insure your .gitignore has config.py in it"""
